sudo: false
language: python
python:
- '3.7'
install:
- pip install pygments lxml setuptools --upgrade
- git clone https://github.com/tabatkins/bikeshed.git
- pip install --editable $PWD/bikeshed
- bikeshed update
script:
- bash "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: "46468fa39e2a"
  - COMMIT_AUTHOR_EMAIL: "plh+deploy@w3.org"
